### ISSUE TITLE
映射的文件夹permission denied

### ISSUE THREAD

**Issue by AAlexDing** [dclemon/Bustag_lemon#2]
已经在宿主机里都给了777权限，但是还是出现permission denied 问题
系统：UNRAID 6.9.2 , docker 20.10.5
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='bustag' --net='bridge' -e TZ="Asia/Shanghai" -e HOST_OS="Unraid" -p '8000:8000/tcp' -v '/mnt/user/appdata/bustag/app/':'/app':'rw' 'dclemon/bustag:0.0.4'
dad443e32ed640649bb1da7c5f291011d445253fa60fdae39111142ef1042e74
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/app/docker/entry.sh": permission denied: unknown.

The command failed.

**Comment by dclemon** [comment]
使用下面的容器
https://registry.hub.docker.com/r/aiastia/bustag/

**Comment by AAlexDing** [comment]
多谢~
